// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCseDT18m5DsSlgq-jpc9YyI3m45zcfJIY',
    appId: '1:47916129934:web:3b9f6be6a4b6a0da3f33df',
    messagingSenderId: '47916129934',
    projectId: 'bookapp-e6672',
    authDomain: 'bookapp-e6672.firebaseapp.com',
    storageBucket: 'bookapp-e6672.firebasestorage.app',
    measurementId: 'G-ZQP0CBHZQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfqmIzSyH6sEcLAyDmb7kh7gp82sFFJ3U',
    appId: '1:47916129934:android:828368cae5bc87e13f33df',
    messagingSenderId: '47916129934',
    projectId: 'bookapp-e6672',
    storageBucket: 'bookapp-e6672.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz4ZsPxG06C2gXNJ0bcKa6GftJHpH4Jqw',
    appId: '1:47916129934:ios:e20980b1f4fea1ad3f33df',
    messagingSenderId: '47916129934',
    projectId: 'bookapp-e6672',
    storageBucket: 'bookapp-e6672.firebasestorage.app',
    iosBundleId: 'com.example.magh',
  );
}
